<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <WarningLevel>8</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <BuildInParallel>false</BuildInParallel>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NT.Blazor.ErrorBoundary\NT.Blazor.ErrorBoundary.csproj" />
    <ProjectReference Include="..\..\NT.Blazor.ErrorBoundary.AspNetCore\NT.Blazor.ErrorBoundary.AspNetCore.csproj" />
  </ItemGroup>

</Project>
